# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://mghtinlynn.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Htin Lynn"
description: Full-Stack Developer | Software Engineer

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Htin Lynn
author-bio: true  # change to false to hide
author-image: profile.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: https://github.com/MgHtinLynn
linkedin: https://www.linkedin.com/in/htin-lynn-8b999193/
medium: https://medium.com/@htinlynn
google-scholar: false
email: htinlin01@gmail.com

# footer information
footer-msg: "Powered using Tailpages"
footer-msg-link: https://github.com/MgHtinLynn/mghtinlynn.github.io

# google analytics
google-analytics: G-DHEB73X636

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

# collections
collections_dir: collections
collections:
  - workExperiences